version: "3.8"

services:
  hestiacp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hestiacp-server"
    restart: "unless-stopped"
    hostname: "${HSTC_HOSTNAME:?Hostname not defined}"
    privileged: true
    depends_on:
      - mariadb
    environment:
      MAIL_ADMIN: "${MAIL_ADMIN:-}"
      AUTOSTART_DISABLED: "${AUTOSTART_DISABLED:-}"
    labels:
      - "Hestia Control Panel"
    ports:
      - "80:80"
      - "443:443"
      - "8083:8083"
      - "3306:3306"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:953:953/tcp"
      - "20:20"
      - "21:21"
      - "12000-12100:12000-12100"
      - "22222:22222"
      - "25:25"
      - "465:465"
      - "587:587"
      - "2525:2525"
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
    volumes:
      - /data/backup:/backup
      - /data/conf:/conf
      - /data/home:/home
      - mariadb-logs:/var/log/mysql
    networks:
      - default

  mariadb:
    image: mariadb:10.6
    container_name: "hestiacp-mariadb"
    restart: "unless-stopped"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_ROOT_HOST: "%"
      MARIADB_INITDB_SKIP_TZINFO: 1
    volumes:
      - /data/mariadb:/var/lib/mysql
      - mariadb-logs:/var/log/mysql
    command: [ "mariadbd", "--max-connections=1000", "--max-user-connections=150", "--max-allowed-packet=128M" ]
    networks:
      - default

volumes:
  mariadb-logs:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
